grails-app/controllers/browzy/VideoController.groovy
package browzy

import grails.plugin.springsecurity.annotation.Secured

@Secured([DbConst.ROLE_ADMIN])
class VideoController {

    def videoService
    def securityService
    def sitemapService

    def add() {
        render view: "edit.gsp", model: [
                action: 'add'
//                user  : securityService.getLoggedInUser()
        ]
    }

    def publish() {
        User user = securityService.getLoggedInUser()
        if (user) {
            def posts = videoService.save(params, user, PostStatus.ACTIVE)
            for (Post post : posts) {
                sitemapService.postCreated(post)
            }
        }
        redirect controller: "front"
    }

    def save() {
        println params
        redirect controller: "front"
    }
}

grails-app/views/video/_post.gsp
<%@ page import="browzy.DbConst" %>
<div class="post_block video_block add_video ui-sortable-handle ${it ? 'visible' : ''}">
    <asset:image src="red_arrow.png" class="red_arrow" alt="" />
    <div class="row">
        <div class="gray_rounded_block col-sm-12 col-md-3">
            <asset:image src="vid.png" class="center-block" alt="" />
            <iframe style="display:none;" frameborder='0' webkitAllowFullScreen mozallowfullscreen allowfullscreen></iframe>
        </div>
        <div class="col-sm-12 col-md-8 inputs">
            <p>Title</p>
            <input type="text" class="form-control input" name="title"
                   placeholder="Maximum title length is ${DbConst.MAX_POST_TITLE_SIZE}" maxlength="${DbConst.MAX_POST_TITLE_SIZE}"/>
            <p>Description</p>
            <textarea class="form-control" name="text"
                      placeholder="Maximum description length is ${DbConst.MAX_TEXT_SIZE}" maxlength="${DbConst.MAX_TEXT_SIZE}"></textarea>
            <p>Video link</p>
            <input type="text" class="form-control input" name="videolink" maxlength="${DbConst.MAX_TEXT_SIZE}" />
            <p>Tags</p>
            <div class="video-tags-input">
                <input type="text" class="form-control input" name="tags"/>
            </div>
            <p>Source link, if required</p>
            <input type="text" class="form-control input" name="source"
                   placeholder="Maximum link length is ${DbConst.MAX_LINK_SIZE}" maxlength="${DbConst.MAX_LINK_SIZE}" />
        </div>
    </div>
</div>

grails-app/views/video/edit.gsp
<%@ page import="browzy.DbConst" %>
<!doctype html>
<html>
<head>
    <asset:stylesheet src="bootstrap-tagsinput.css"/>

    <asset:javascript src="bootstrap-tagsinput.min.js"/>

    <script>
        var MAX_POST_TITLE_SIZE = ${DbConst.MAX_POST_TITLE_SIZE}
        var MAX_TEXT_SIZE = ${DbConst.MAX_TEXT_SIZE}
        var MAX_CATEGORIES = ${DbConst.MAX_CATEGORIES}
        var MAX_LINK_SIZE = ${DbConst.MAX_LINK_SIZE}
    </script>
</head>
<body>
<div id="inner_page">
    <div class="add_video_header" id ="navigation">
        <div role="presentation" data-count = "4">4 SECTIONS</div>
        <div role="presentation" data-count = "6">6 SECTIONS</div>
        <div role="presentation" data-count = "8">8 SECTIONS</div>
    </div>
    <div class="container">
        <g:render template="post"/>
        <g:uploadForm controller="video">
            <div class="clearfix"></div>
            <div class="sortable ui-sortable" id="videoBlocks">
            </div>

            <div class="row add_post_buttons add_video">
                <div class="col-sm-3 col-sm-offset-3 publish_button">
                    <button name="_action_publish">Publish</button>
                </div>
                <div class="col-sm-3 save_button">
                    <button name="_action_save">Save</button>
                </div>
            </div>
        </g:uploadForm>
    </div>
</div>

<asset:javascript src="video.js"/>

</body>
</html>